class LoginFields:
    FIELD_LOGIN_USER = '#vUSUARIO'
    FIELD_LOGIN_PASSWORD = '#vSENHA'
    BUTTON_LOGIN = '#ENTER'
    BUTTON_CLOSE_POPUP = '#gxp0_cls'

class HomeFields:
    BUTTON_LOGOUT = '#gxp0_cls'
    BUTTON_SEARCH = '#vPESQUISA_MPAGE'
    ICON_MENU = '#DIVLOGO_MPAGE'
    IFRAME_BRANCH = '#gxp0_ifrm'
    BUTTON_SWITCH_BRANCH = '#TXTEMPRESAFILIAL_MPAGE'
    DROPDOWN_BRANCH = '#vE35FILIAL'
    BUTTON_CONFIRM_BRANCH = '#BTNENTER'

class HomeMenuFields:
    MODULES = "#MPW0100GdmenumodulosContainerTbl"
    MODULE_FISCAL = "#MPW0100GRID1TABLE_0008"

class FiscalFields:
    SIDEBAR_FISCAL = "//*[@id='cssmenu']/ul/li[9]/a"
    OPTION_INVOICE = "//*[@id='cssmenu']/ul/li[9]/ul/li[1]/a"
    BUTTON_CLEAN = "#CLEANFILTERS"
    FIELD_KEY = "#vE161CHAVENFE"
    DROPDOWN_SITUATION_MANIFESTED = "#vE161MDSITUACAO"
    DROPDOWN_SITUATION = "#vE161NFESITUACAO"
    DROPDOWN_DOCUMENT_TYPE = "#vE161DOCUMENTOTIPO"
    BUTTON_SEARCH = "#IMGPESQUISA"
    BUTTON_LAUNCH = "#vLANCARNFE_0001"
    BUTTON_VIEW = "#vVISUALIZARNFE_0001"
    TITLE_FISCAL = "#TXTITULO"
    ROTINE = "2988"

class ImportXMLFields:
    TITLE_IMPORT_XML = "#TXTITULO"
    FIELD_OPERATION = "#W0021vE22CODOPE"
    BUTTON_NEXT = "#W0021BTNWIZARDNEXT"
    BUTTON_CONFIRM_NEXT = "#W0021DVELOP_CONFIRMPANEL_WIZARDNEXTContainer_SaveButton"
    ROTINE = "1339"

class LaunchNFSe:
    TITLE_LAUNCH_NFSE = "#TXTITULO"
    FIELD_RELEASE_DATE = "#W0021W0015vE11DATAL"
    FIELD_CHECKER = "#W0021W0015E11CONFERENTE"
    FIELD_VENDOR = "#W0021W0015E11VENDEDORID"
    FIELD_PAYMENT_POLICY = "#W0021W0015E69POLPRAZO"
    FIELD_COST_CENTER = "#W0021W0015E11CCUSTO"
    TAB_TOTALS = "#Tab_W0021W0015GXUITABSPANEL_TABSContainerpanel1"
    TAB_TAXES = "#W0021W0015vSELETORIMPOSTO1"
    TABLE_INSTALLMENTS = "#W0021W0015TABLECONTENT"
    TABLE_ITEMS = "#W0021W0015GridContainerTbl"
    BUTTON_NEXT = "#W0021W0015BTNTRN_ENTER"
    BUTTON_NEXT_ITEMS_TAXES = "#W0021BTNWIZARDNEXT"
    BUTTON_CONFIRM = "#W0021W0015BTNENTER"
    ROTINE = "1020"

FILTERS_SITUATION = {
    "situation_manifested": "Todos",
    "document_type": "Nota Fiscal",
    "situation": "Uso Autorizado no Momento da Consulta",
}