class LoginFields:
    FIELD_LOGIN_USER = '#vUSUARIO'
    FIELD_LOGIN_PASSWORD = '#vSENHA'
    BUTTON_LOGIN = '#ENTER'
    BUTTON_CLOSE_POPUP = '#gxp0_cls'

class HomeFields:
    BUTTON_LOGOUT = '#gxp0_cls'
    BUTTON_SEARCH = '#vPESQUISA_MPAGE'
    ICON_MENU = '#DIVLOGO_MPAGE'
    IFRAME_BRANCH = '#gxp0_ifrm'
    BUTTON_SWITCH_BRANCH = '#TXTEMPRESAFILIAL_MPAGE'
    DROPDOWN_BRANCH = '#vE35FILIAL'
    BUTTON_CONFIRM_BRANCH = '#BTNENTER'

class HomeMenuFields:
    MODULES = "#MPW0100GdmenumodulosContainerTbl"
    MODULE_FISCAL = "#MPW0100GRID1TABLE_0008"
    MODULE_STOCK = "#MPW0100GRID1TABLE_0006"

class StockFields:
    SIDEBAR_STOCK = "//*[@id='cssmenu']/ul/li[4]"
    OPTION_PRODUCT_STOCK = "//*[@id='cssmenu']/ul/li[4]/ul/li[1]/a"
    OPTION_REGISTER_STOCK = "//*[@id='cssmenu']/ul/li[4]/ul/li[1]/ul/li[1]/a"
    BUTTON_CLEAN = "#CLEANFILTERS"
    FIELD_PRODUCT = "#vE18CODPRO"
    BUTTON_SEARCH = "#IMGPESQUISA"
    BUTTON_EDIT = "#vEDITAR_0001"

class ProductFields:
    TAB_TAX ="#Tab_GXUITABSPANEL_TABSPRODUTOContainerpanel4"
    DROPDOWN_ORIGIN = "#E18CST1"
    BUTTON_SAVE = "#BTNTRN_ENTER"
    ROTINE = "1068"
    TITLE_PRODUCT = "#TXTITULO"
    
class FiscalFields:
    SIDEBAR_FISCAL = "//*[@id='cssmenu']/ul/li[9]/a"
    OPTION_INVOICE = "//*[@id='cssmenu']/ul/li[9]/ul/li[1]/a"
    BUTTON_CLEAN = "#CLEANFILTERS"
    FIELD_KEY = "#vE161CHAVENFE"
    DROPDOWN_SITUATION_MANIFESTED = "#vE161MDSITUACAO"
    DROPDOWN_SITUATION = "#vE161NFESITUACAO"
    DROPDOWN_DOCUMENT_TYPE = "#vE161DOCUMENTOTIPO"
    BUTTON_SEARCH = "#IMGPESQUISA"
    BUTTON_LAUNCH = "#vLANCARNFE_0001"
    BUTTON_VIEW = "#vVISUALIZARNFE_0001"
    TITLE_FISCAL = "#TXTITULO"
    ROTINE = "2988"
    TEXT_SITUATION_MANIFESTED = "#span_E161MDSITUACAO_0001"
    TEXT_DOCUMENT_TYPE = "#span_E161DOCUMENTOTIPO_0001"
    TEXT_SITUATION = "#span_E161NFESITUACAO_0001"
    CHECKBOX_SELECT_INVOICE = "#vSELECTED_0001"
    BUTTON_MANIFEST = "#BTNMANIFESTAR"
    OPTION_CONFIRM_OPERATION = "input#vE62MD_TPEVENTO3"
    BUTTON_MANIFEST_CONFIRM = "#BTNENTER"
    IFRAME_CONFIRM_OPERATION = "#gxp0_ifrm"

class ManualSelectionPopupFields:
    POPUP_CONFIRM_OPERATION = "#W0208TABLECAMPOS"
    BUTTON_UPDATE_SITUATION = "#W0208vUPDATERATEIO_0001"
    BUTTON_CONFIRM_SITUATION = "#W0208BTNENTER"

class SelectEventPopupFields:
    POPUP_CONFIRM_EVENT = "#W0208W0064TABLECAMPOS"
    DROPDOWN_SITUATION = "#W0208W0064vE161MDSITUACAO"
    BUTTON_CONFIRM_EVENT = "#W0208W0064BTNENTER"

class ImportXMLFields:
    TITLE_IMPORT_XML = "#TXTITULO"
    FIELD_OPERATION = "#W0021vE22CODOPE"
    BUTTON_NEXT = "#W0021BTNWIZARDNEXT"
    BUTTON_CONFIRM_NEXT = "#W0021DVELOP_CONFIRMPANEL_WIZARDNEXTContainer_SaveButton"
    ROTINE = "1339"

class LaunchNFSe:
    TITLE_LAUNCH_NFSE = "#TXTITULO"
    FIELD_RELEASE_DATE = "#W0021W0015vE11DATAL"
    FIELD_CHECKER = "#W0021W0015E11CONFERENTE"
    FIELD_VENDOR = "#W0021W0015E11VENDEDORID"
    FIELD_PAYMENT_POLICY = "#W0021W0015E69POLPRAZO"
    FIELD_COST_CENTER = "#W0021W0015E11CCUSTO"
    TAB_TOTALS = "#Tab_W0021W0015GXUITABSPANEL_TABSContainerpanel1"
    TAB_TAXES = "#W0021W0015vSELETORIMPOSTO1"
    TABLE_INSTALLMENTS = "#W0021W0015TABLECONTENT"
    TABLE_ITEMS = "#W0021W0015GridContainerTbl"
    BUTTON_NEXT = "#W0021W0015BTNTRN_ENTER"
    BUTTON_NEXT_ITEMS_TAXES = "#W0021BTNWIZARDNEXT"
    BUTTON_CONFIRM = "#W0021W0015BTNENTER"
    ROTINE = "1020"

FILTERS_SITUATION = {
    "situation_manifested": "Todos",
    "document_type": "Nota Fiscal",
    "situation": "Uso Autorizado no Momento da Consulta",
}

SITUATION_APPROVED = {
    "situation_manifested_approved": "Confirmada Operação",
    "situation_manifested_not_approved": ["Sem Manifestação do Destinatário", "Ciência"],
    "situation_approved": "Uso Autorizado no Momento da Consulta",
    "document_type_approved": "Nota Fiscal"
}
